[package]
name = "stylet-wasm"
description = "WebAssembly bindings for the stylet playground"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
stylet-compile.workspace = true
stylet-fmt.workspace = true
stylet-resolve.workspace = true
stylet-syntax.workspace = true
wasm-bindgen = "0.2.129"
