[package]
name = "stylet-compile"
description = "Compiles stylet to CSS"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
stylet-syntax.workspace = true
stylet-resolve.workspace = true

[dev-dependencies]
expect-test = "1.5.1"
