[package]
name = "stylet-resolve"
description = "Import resolution and virtual file system for stylet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
stylet-syntax.workspace = true
